### ISSUE TITLE
OutOfMemoryError irreversibly kills monitoring thread

### ISSUE THREAD

**Issue by akhavr** [akhavr/vidcap#2]
Should gracefully restart the thread

```
Exception in thread WebcamVideoStream:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/vidcap/.env/lib/python3.7/site-packages/imutils/video/webcamvideostream.py", line 34, in update
    (self.grabbed, self.frame) = self.stream.read()
cv2.error: OpenCV(4.1.0) /home/pi/opencv-python/opencv/modules/core/src/alloc.cpp:55: error: (-4:Insufficient memory) Failed to allocate 921600 bytes in function 'OutOfMemoryError'


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "object.py", line 106, in <lambda>
    t = threading.Thread(target=lambda: detector.detect())
  File "/home/pi/vidcap/video.py", line 272, in detect
    self.outputFrame = frame.copy()
MemoryError: Unable to allocate 352. KiB for an array with shape (300, 400, 3) and data type uint8

```

**Comment by akhavr** [comment]
Fixed in e602816
